config/routes.rb
QRcodeOrder::Application.routes.draw do
  resources :branches

  resources :users
  match '/signin', to: 'sessions#new',				via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :tables

  resources :authentications
  match '/update_statu/:id', to: 'authentications#update_statu',				via: 'put'
  match '/edit_table/:id', to: 'authentications#edit_table',						via: 'get'
  match '/update_table/:id', to: 'authentications#update_table',				via: 'put'

  resources :menus

  resources :little_menus
  match '/branch_little_menus/:id', 					to: 'little_menus#branch_little_menus',						via: 'get'
  match '/chuancai_index', 										to: 'little_menus#chuancai_index',								via: 'get'
	match '/update_little_menus_zhunbei/:id', 	to: 'little_menus#update_zhunbei',								via: 'put'
	match '/update_little_menus_chuancai/:id',  to: 'little_menus#update_chuancai',								via: 'put'

  resources :foods

  resources :food_types

  root 'static_pages#home'

end

app/controllers/food_types_controller.rb
class FoodTypesController < ApplicationController
  before_action :set_food_type, only: [:show, :edit, :update, :destroy]

  # GET /food_types
  # GET /food_types.json
  def index
    @food_types = FoodType.all
  end

  # GET /food_types/1
  # GET /food_types/1.json
  def show
    @foods = @food_type.foods;
  end

  # GET /food_types/new
  def new
    @food_type = FoodType.new
  end

  # GET /food_types/1/edit
  def edit
  end

  # POST /food_types
  # POST /food_types.json
  def create
    @food_type = FoodType.new(food_type_params)

    respond_to do |format|
      if @food_type.save
        format.html { redirect_to @food_type, notice: 'Food type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @food_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_types/1
  # PATCH/PUT /food_types/1.json
  def update
    respond_to do |format|
      if @food_type.update(food_type_params)
        format.html { redirect_to @food_type, notice: 'Food type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_types/1
  # DELETE /food_types/1.json
  def destroy
    @food_type.destroy
    respond_to do |format|
      format.html { redirect_to food_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_type
      @food_type = FoodType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_type_params
      params.require(:food_type).permit(:name)
    end
end

app/helpers/food_types_helper.rb
module FoodTypesHelper
end

app/views/food_types/_form.html.erb
<%= form_for(@food_type) do |f| %>
  <% if @food_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_type.errors.count, "error") %> prohibited this food_type from being saved:</h2>

      <ul>
      <% @food_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_types/edit.html.erb
<h1>Editing food_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_type %> |
<%= link_to 'Back', food_types_path %>

app/views/food_types/index.html.erb
<h1>Listing food_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @food_types.each do |food_type| %>
      <tr>
        <td><%= food_type.name %></td>
        <td><%= link_to 'Show', food_type %></td>
        <td><%= link_to 'Edit', edit_food_type_path(food_type) %></td>
        <td><%= link_to 'Destroy', food_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food type', new_food_type_path %>

app/views/food_types/new.html.erb
<h1>New food_type</h1>

<%= render 'form' %>

<%= link_to 'Back', food_types_path %>

app/views/food_types/show.html.erb
<head>
</head>
<div class="container">
<% provide(:title, @food_type.name) %>

<% l = @foods.length %>
<% i = 0 %>
<% @foods.each do |food| %>
	
	<!-- for computer -->
	<% if i%4 == 0 %>
		<div class="row hidden-xs">
	<% end %>
	
	<%= link_to  food, remote: true, class: "show-food-modal white-panel col-sm-3" do %>
		<img src="/images/foods/test.jpg" alt="车酷烧烤">
		<h4 class="text-center"><%= food.name %> <span class="glyphicon glyphicon-yen" aria-hidden="true"></span><span><%= food.price %></span></h4>
    <p></p>
	<% end %>
	
	<% if i%4 == 3 %>
		</div>
	<% end %>
	
	<% i = i + 1 %>
	<% if i == l %>
		</div>
	<% end %>

<% end %>

<% i = 0 %>
<% @foods.each do |food| %>

	<!-- for mobile -->
	<% if i%3 == 0 %>
		<div class="row visible-xs-block">
	<% end %>
	
	<%= link_to  food, remote: true, class: "show-food-modal white-panel col-xs-4" do %>
		<img src="/images/foods/test.jpg" alt="车酷烧烤">
		<h4 class="text-center"><%= food.name %> <span class="glyphicon glyphicon-yen" aria-hidden="true"></span><span><%= food.price %></span></h4>
    <p></p>
	<% end %>
	
	<% if i%3 == 2 %>
		</div>
	<% end %>
	
	<% i = i + 1 %>
	<% if i == l %>
		</div>
	<% end %>

<% end %>

<!-- modal -->
<div id="foodModal" class="modal fade" ndex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
      	<h3 class="text-center"><span id="show-food-name"></span> <span class="glyphicon glyphicon-yen" aria-hidden="true"></span><span id="show-food-price"></span></h3>
      	<div class="hide"><p6 id="food-id"></p6></div>
      	<img src="/images/foods/test.jpg" " alt="车酷烧烤" >      
      </div>
      
      <div class="modal-footer">
      	<div class="container-fluid">
      		<div class="row">
      			<input class="col-sm-2 col-xs-4" id="food-number" type="text" value="5" />
      			<button id="add-to-menu" class="btn btn-small btn-warning pull-right col-sm-5 col-xs-7 col-sm-offset-1" data-dismiss="modal" type="button">加入菜单</button>
      			<input id="myRange-desk" onmousemove="rangeDesk()" class="hidden-xs" type="range" name="points" value="5" min="1" max="50">
      			<input id="myRange-mobile" ontouchmove="rangeMobile()" class="visible-xs-block" type="range" name="points" value="5" min="1" max="30">
      		</div>
      	</div>
      </div>
    </div>    
  </div>
</div>

<hr>

</div> <!-- container -->


<script>
function rangeDesk() {
    var x = document.getElementById("myRange-desk").value;
    document.getElementById("food-number").value = x;
}
function rangeMobile() {
    var x = document.getElementById("myRange-mobile").value;
    document.getElementById("food-number").value = x;
}
</script>