config/routes.rb
QRcodeOrder::Application.routes.draw do
  resources :branches

  resources :users
  match '/signin', to: 'sessions#new',				via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :tables

  resources :authentications
  match '/update_statu/:id', to: 'authentications#update_statu',				via: 'put'
  match '/edit_table/:id', to: 'authentications#edit_table',						via: 'get'
  match '/update_table/:id', to: 'authentications#update_table',				via: 'put'

  resources :menus

  resources :little_menus
  match '/branch_little_menus/:id', 					to: 'little_menus#branch_little_menus',						via: 'get'
  match '/chuancai_index', 										to: 'little_menus#chuancai_index',								via: 'get'
	match '/update_little_menus_zhunbei/:id', 	to: 'little_menus#update_zhunbei',								via: 'put'
	match '/update_little_menus_chuancai/:id',  to: 'little_menus#update_chuancai',								via: 'put'

  resources :foods

  resources :food_types

  root 'static_pages#home'

end

app/models/little_menu.rb
class LittleMenu < ActiveRecord::Base
  attr_accessible :menu_id, :food_id, :number, :remark
  
  has_one :food
  belongs_to :food
  belongs_to :menu
  
  validates :menu_id, presence:true
  validates :food_id, presence:true
  validates_numericality_of :number, :greater_than => 0
end

app/controllers/little_menus_controller.rb
# -*- encoding : utf-8 -*-
class LittleMenusController < ApplicationController
  before_action :set_little_menu, only: [:show, :edit, :update, :destroy, :update_chuancai, :update_zhunbei]
  skip_before_filter :verify_authenticity_token, :only => [:create, :destroy]
	before_action :valid_authentication, only: [:create, :destroy]
	before_action :signed_in_user, only: [:index, :show, :branch_little_menus, :chuancai_index, :update_zhunbei, :update_chuancai, :new, :edit, :update]

  # GET /little_menus
  # GET /little_menus.json
  def index
    @little_menus = LittleMenu.all
  end

  # GET /little_menus/1
  # GET /little_menus/1.json
  def show
  end

	# GEt /branch_little_menus/1
	def branch_little_menus
		@branch = Branch.find(params[:id])
		@menus_false = Menu.where(statu:false).limit(200).order(:updated_at)

		# 筛选出未准备的小单 little_menus_zhunbei_false
		l = @menus_false.length
    if l
      @little_menus_zhunbei_false = []
      i = 0
      while i < l do
        @little_menus_zhunbei_false = @little_menus_zhunbei_false + @menus_false[i].little_menus.where(zhunbei:false, chuancai:false).limit(50).order(:updated_at)
        i += 1
      end
      # 进一步筛选出该部门的小单 branch_little_menus_zhunbei_false 
      l = @little_menus_zhunbei_false.length
      if l
      	@branch_little_menus_zhunbei_false = []
      	i = 0
      	while i < l do
      		if Food.find(@little_menus_zhunbei_false[i].food_id).branch_id == @branch.id
      			@branch_little_menus_zhunbei_false << @little_menus_zhunbei_false[i]
      		end
      		i += 1
      	end
      end
      
    end
    
	end
	
	# GEt /chuancai_index
	def chuancai_index
		@menus_false = Menu.where(statu:false).limit(200).order(:updated_at)

		# 筛选出准备但还未传的小单 little_menus_zhunbei_false
		l = @menus_false.length
    if l
      @little_menus_zhunbei_true_chuancai_false = []
      i = 0
      while i < l do
        @little_menus_zhunbei_true_chuancai_false = @little_menus_zhunbei_true_chuancai_false + @menus_false[i].little_menus.where(zhunbei:true, chuancai:false).limit(50).order(:updated_at)
        i += 1
      end
    end
	
	end

	# PUT /update_little_menus_zhunbei/:id
	def update_zhunbei
		branch = Food.find(@little_menu.food_id).branch_id
		case branch # 身份认证
			when 1 # 吧台
				if !@current_user.jiushui && !@current_user.admin
					redirect_to root_path and return
				end
			when 2 # 后厨
				if !@current_user.zhuachuan && !@current_user.admin
					redirect_to root_path and return
				end
			when 3 # 凉菜
				if !@current_user.jiushui && !@current_user.admin
					redirect_to root_path and return
				end
			else
				flash[:danger] = "无法准备该小单，没有对应的部门！"
				redirect_to root_path and return
		end
		
		if @little_menu.zhunbei
			flash[:danger] = "准备失败！小单已准备！"
			redirect_to '/branch_little_menus/'+branch.to_s
		else
			if @little_menu.update(zhunbei:true)
				flash[:success] = "准备成功！"
      	redirect_to '/branch_little_menus/'+branch.to_s
    	else
    		flash[:danger] = "准备失败！"
      	redirect_to '/branch_little_menus/'+branch.to_s
    	end
    end
		
	end
	
	# PUT /update_little_menus_chuancai/:id
	def update_chuancai
		branch = Food.find(@little_menu.food_id).branch_id
		# 验证是否具备传菜权限
		if !@current_user.chuancai && !@current_user.admin
			redirect_to root_path and return
		end
		
		if @little_menu.chuancai
			flash[:danger] = "确认传菜失败！小单已传递！"
			redirect_to '/chuancai_index'
		else
			if @little_menu.update(chuancai:true)
				flash[:success] = "确认传菜成功！"
      	redirect_to '/chuancai_index'
    	else
    		flash[:danger] = "确认传菜失败！"
      	redirect_to '/chuancai_index'
    	end
    end
	
	end

  # GET /little_menus/new
  def new
    @little_menu = LittleMenu.new
  end

  # GET /little_menus/1/edit
  def edit
  end

  # POST /little_menus
  # POST /little_menus.json
  def create
    @menu = @current_authentication.menus.find_by_statu(true)
      
		if @menu
      @little_menu = LittleMenu.new(menu_id: @menu.id, food_id: params[:food_id], number: params[:number])
    else
      @menu = Menu.new(authentication_id: @current_authentication.id)
        if @menu.save
          @little_menu = LittleMenu.new(menu_id: @menu.id, food_id: params[:food_id], number: params[:number])
        else
          flash[:error] = "大菜单存储错误！"
        end
		end
      
    respond_to do |format|
      if @little_menu.save
        format.json { render json: @little_menu }
      else
        format.html
        format.json { render json: @little_menu.errors }
      end
    end
  end

  # PATCH/PUT /little_menus/1
  # PATCH/PUT /little_menus/1.json
  def update
    respond_to do |format|
      if @little_menu.update(little_menu_params)
        format.html { redirect_to @little_menu, notice: 'Little menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @little_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /little_menus/1
  # DELETE /little_menus/1.json
  def destroy
    @little_menu.destroy
    respond_to do |format|
      format.html { redirect_to little_menus_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_little_menu
      @little_menu = LittleMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def little_menu_params
      params.require(:little_menu).permit(:menu_id, :food_id, :number, :remark)
    end
end

app/helpers/little_menus_helper.rb
module LittleMenusHelper
end

app/views/little_menus/_form.html.erb
<%= form_for(@little_menu) do |f| %>
  <% if @little_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@little_menu.errors.count, "error") %> prohibited this little_menu from being saved:</h2>

      <ul>
      <% @little_menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_id %><br>
    <%= f.number_field :menu_id %>
  </div>
  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.text_field :food_id %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :remark %><br>
    <%= f.text_field :remark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/little_menus/branch_little_menus.html.erb
<% provide(:title, @branch.name+"准备") %>
<head></head>

<button id="shuaxin" type="button" class="btn btn-default btn-circle btn-xl"><i class="glyphicon glyphicon-repeat"></i></button>

<div class="container container-little-menus">
    <div class="row">
        
        <% @branch_little_menus_zhunbei_false.each do |little_menu| %>
        <div class="col-md-3 little-menu-zhunbei">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="text-center"><%= @branch.name %></h4>
                </div>
                <div class="panel-body text-center">
                	<strong><%= Food.find(little_menu.food_id).name %> / <%= little_menu.number %></strong>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item"><i class="icon-ok text-danger"></i>桌号： <%= Table.find(Authentication.find(Menu.find(little_menu.menu_id).authentication_id).table_id).name %></li>
                    <li class="list-group-item"><i class="icon-ok text-danger"></i>时间： <%= little_menu.updated_at.to_time %></li>
                </ul>
                <div class="panel-footer">
                	<%= form_for(little_menu, url: '/update_little_menus_zhunbei/'+little_menu.id.to_s, method: :put) do |f| %>
										<%= f.submit("确认准备", {class: "btn btn-lg btn-block btn-info", data: { confirm: '确认准备？' }}) %>
									<% end %>
                </div>
            </div>
        </div>
        <% end %>        
        
    </div>
</div>

<script>
	function zhunbeinum() {
  var zhunbei = $('.container-little-menus').find('.little-menu-zhunbei');
  
  if(zhunbei.length < 5) 
    window.location.reload(true);
  else 
  setTimeout(zhunbeinum, 30000);
  }
	
	setTimeout(zhunbeinum, 30000);
</script>

app/views/little_menus/chuancai_index.html.erb
<% provide(:title, "传菜") %>
<head>
</head>

<button id="shuaxin" type="button" class="btn btn-default btn-circle btn-xl"><i class="glyphicon glyphicon-repeat"></i></button>
<button id="kaochuan" type="button" class="btn btn-warning btn-circle btn-lg"></button>
<button id="jiushui" type="button" class="btn btn-info btn-circle btn-lg"></button>
<button id="liangcai" type="button" class="btn btn-success btn-circle btn-lg"></button>

<div class="container container-little-menus">
    <div class="row">   
      
        <% @little_menus_zhunbei_true_chuancai_false.each do |little_menu| %>
        	<% @branch = Branch.find(Food.find(little_menu.food_id).branch_id) %>
        <div class="col-md-3 <% if @branch.id == 1 %>little-menu-jiushui<% elsif @branch.id == 3%>little-menu-liangcai<% else %>little-menu-kaochuan<%end%>">
            <div class="panel <% if @branch.id == 1 %>panel-info<% elsif @branch.id == 3%>panel-success<% else %>panel-warning<%end%>">
                <div class="panel-heading">
                    <h4 class="text-center"><%= @branch.name %></h4>
                </div>
                <div class="panel-body text-center">
                	<strong><%= Food.find(little_menu.food_id).name %> / <%= little_menu.number %></strong>
                </div>
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item"><i class="icon-ok text-danger"></i>桌号： <%= Table.find(Authentication.find(Menu.find(little_menu.menu_id).authentication_id).table_id).name %></li>
                    <li class="list-group-item"><i class="icon-ok text-danger"></i>时间： <%= little_menu.updated_at.to_time %></li>
                </ul>
                <div class="panel-footer">
                	<%= form_for(little_menu, url: '/update_little_menus_chuancai/'+little_menu.id.to_s, method: :put) do |f| %>
                		<% if @branch.id == 1%>
											<%= f.submit("确认已传递", {class: "btn btn-lg btn-block btn-info", data: { confirm: '确认已经传递？' }}) %>
										<% elsif @branch.id == 3 %>
											<%= f.submit("确认已传递", {class: "btn btn-lg btn-block btn-success", data: { confirm: '确认已经传递？' }}) %>
										<% else %>
											<%= f.submit("确认已传递", {class: "btn btn-lg btn-block btn-warning", data: { confirm: '确认已经传递？' }}) %>
										<% end %>
									<% end %>
                </div>
            </div>
        </div>
        <% end %>        
        
    </div>
</div>

<script>
showlittlemenus(getCookie('branch'));

function chuancai() {
	var branch = getCookie('branch');
  var chuancainum = $('.container-little-menus').find('.little-menu-'+branch);
  
  if(chuancainum.length < 5 && branch != "")
    window.location.reload(true);
  else 
  	setTimeout(chuancai, 30000);
}
	
	setTimeout(chuancai, 30000);

function setCookie(cname,cvalue,exdays)
{
var d = new Date();
d.setTime(d.getTime()+(exdays*24*60*60*1000));
var expires = "expires="+d.toGMTString();
document.cookie = cname + "=" + cvalue + "; " + expires;
}

function getCookie(cname)
{
var name = cname + "=";
var ca = document.cookie.split(';');
for(var i=0; i<ca.length; i++) 
  {
  var c = ca[i].trim();
  if (c.indexOf(name)==0) return c.substring(name.length,c.length);
}
return "";
}

function showlittlemenus(branch) {
	if (branch=='jiushui' || branch=='liangcai' || branch=='kaochuan')	{
		$('.container-little-menus').find('.little-menu-jiushui').addClass('hide');
		$('.container-little-menus').find('.little-menu-liangcai').addClass('hide');
		$('.container-little-menus').find('.little-menu-kaochuan').addClass('hide');
		$('.container-little-menus').find('.little-menu-' + branch).removeClass('hide');
		setCookie('branch', branch, 30);}
}

$('#kaochuan').on('click', function (event){
	showlittlemenus('kaochuan');
})

$('#jiushui').on('click', function (event){
	showlittlemenus('jiushui');
})

$('#liangcai').on('click', function (event){
	showlittlemenus('liangcai');
})

</script>

app/views/little_menus/edit.html.erb
<h1>Editing little_menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @little_menu %> |
<%= link_to 'Back', little_menus_path %>

app/views/little_menus/index.html.erb
<h1>Listing little_menus</h1>

<table>
  <thead>
    <tr>
      <th>Menu</th>
      <th>Food</th>
      <th>Number</th>
      <th>Remark</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @little_menus.each do |little_menu| %>
      <tr>
        <td><%= little_menu.menu_id %></td>
        <td><%= little_menu.food_id %></td>
        <td><%= little_menu.number %></td>
        <td><%= little_menu.remark %></td>
        <td><%= link_to 'Show', little_menu %></td>
        <td><%= link_to 'Edit', edit_little_menu_path(little_menu) %></td>
        <td><%= link_to 'Destroy', little_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Little menu', new_little_menu_path %>

app/views/little_menus/new.html.erb
<h1>New little_menu</h1>

<%= render 'form' %>

<%= link_to 'Back', little_menus_path %>

app/views/little_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu:</strong>
  <%= @little_menu.menu_id %>
</p>

<p>
  <strong>Food:</strong>
  <%= @little_menu.food_id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @little_menu.number %>
</p>

<p>
  <strong>Remark:</strong>
  <%= @little_menu.remark %>
</p>

<%= link_to 'Edit', edit_little_menu_path(@little_menu) %> |
<%= link_to 'Back', little_menus_path %>