config/routes.rb
QRcodeOrder::Application.routes.draw do
  resources :branches

  resources :users
  match '/signin', to: 'sessions#new',				via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :tables

  resources :authentications
  match '/update_statu/:id', to: 'authentications#update_statu',				via: 'put'
  match '/edit_table/:id', to: 'authentications#edit_table',						via: 'get'
  match '/update_table/:id', to: 'authentications#update_table',				via: 'put'

  resources :menus

  resources :little_menus
  match '/branch_little_menus/:id', 					to: 'little_menus#branch_little_menus',						via: 'get'
  match '/chuancai_index', 										to: 'little_menus#chuancai_index',								via: 'get'
	match '/update_little_menus_zhunbei/:id', 	to: 'little_menus#update_zhunbei',								via: 'put'
	match '/update_little_menus_chuancai/:id',  to: 'little_menus#update_chuancai',								via: 'put'

  resources :foods

  resources :food_types

  root 'static_pages#home'

end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :price, :food_type_id
  
  belongs_to :food_type
  has_many :little_menus
  belongs_to :little_menu
  
  validates :name, presence:true, length: { maximum: 50 }
  validates :price, presence:true
  validates_numericality_of :price, :greater_than_or_equal_to => 0
  validates :food_type_id, presence:true
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  attr_accessible :name
  
  has_many :foods
  
  validates :name, presence:true, length: { maximum: 50 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render action: 'show', status: :created, location: @food }
      else
        format.html { render action: 'new' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:food_type_id, :name, :price)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_type_id %><br>
    <%= f.number_field :food_type_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<h1>Listing foods</h1>

<table>
  <thead>
    <tr>
      <th>Food type</th>
      <th>Name</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.food_type_id %></td>
        <td><%= food.name %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<div class="dropdown dropdown-accordion" data-accordion="#accordion">
  <a data-toggle="dropdown" href="#" class="btn btn-primary">Dropdown trigger <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    <li>
      <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                Unit 1
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
              <a href="#">Item a</a><br>
              <a href="#">Item b</a>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                Unit 2
              </a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <a href="#">Item a</a><br>
              <a href="#">Item b</a><br>
              <a href="#">Item c</a>
            </div>
          </div>
        </div>
      </div>
    </li>
  </ul>
</div>

<script>
// Collapse accordion every time dropdown is shown
$('.dropdown-accordion').on('show.bs.dropdown', function (event) {
  var accordion = $(this).find($(this).data('accordion'));
  accordion.find('.panel-collapse.in').collapse('hide');
});

// Prevent dropdown to be closed when we click on an accordion link
$('.dropdown-accordion').on('click', 'a[data-toggle="collapse"]', function (event) {
  event.preventDefault();
  event.stopPropagation();
  $($(this).data('parent')).find('.panel-collapse.in').collapse('hide');
  $($(this).attr('href')).collapse('show');
})
</script>

app/views/foods/show.js.erb
$('#show-food-name').html("<%= @food.name %>");
$('#show-food-price').html("<%= @food.price %>");
$('#food-id').html("<%= @food.id %>");